For vendors page: Create new page, add newsletter
cal-itp/mobility-marketplace pull request #503
Opened 2023-12-04 20:43 UTC by machikoyasuda

closes #499

- creates new page
- adds newsletter sign up template

2023-12-04 22:18 UTC, machikoyasuda commented
This is the first PR for the For Vendors page - and is now ready for review. All subsequent PRs will go _into_ this PR. 

When this PR is approved, I will *not* merge it in yet. This PR will be merged at the very end, when all the PRs are done.

FYI @thekaveman @angela-tran

2023-12-07 00:45 UTC, thekaveman approved these changes
:mailbox_with_mail:

2023-12-07 20:28 UTC, machikoyasuda commented
@mrose914 https://deploy-preview-503--cal-itp-mobility-marketplace.netlify.app/for-vendors is ready for final review

2023-12-07 21:42 UTC, thekaveman requested changes
1 tiny fix that I didn't notice from the FAQ PR

2023-12-07 21:42 UTC, thekaveman commented on src/for-vendors.html
> +          <a href="/">calitp.org</a>.
Oops, looks like this `href` is wrong, needs to point to `calitp.org`.

2023-12-08 00:32 UTC, thekaveman approved these changes
Approved pending any updates from @mrose914

2023-12-08 04:55 UTC, merged